version: "3.9"
services:
  wordpress:
    build: ./docker/
    image: wordpress:v1
    container_name: wordpress
    hostname: wordpress
    command: bash -c "service apache2 start && service mysql start && tail -f /dev/null"
    ports:
      - "80:80"


      


      