version: "3.9"
services:
  wordpress:
    build: ./docker/
    image: wordpress:v1
    container_name: wordpress
    hostname: wordpress
    #command: ["tail", "-f", "/dev/null"]
    #command: ["apachectl", "-D", "FOREGROUND", "&&", "service", "mysqld", "start"]
    #command: ["apachectl", "-D", "FOREGROUND"]
    #command: ["service", "mysqld", "start"]
    #command: bash -c "service mysqld start && apachectl -D FOREGROUND"
    command: bash -c "apachectl -D FOREGROUND && /etc/init.d/mysql start"
    ports:
      - "80:80"


      


      